name: Coolify Webhook Trigger

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Trigger Coolify Deploy
        run: |
          echo "Enviando requisição de deploy para Coolify..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -X GET \
            -H "Authorization: Bearer 1|ucxqam9OaI4SGTuNfmCeXvZ6NHrbs0McdeMfEFJb35beb3e1" \
            "https://dev.lkgiovani.com/api/v1/deploy?uuid=s8s0oksoks4c4s04ckckoggw&force=false")

          if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
            echo "Deploy iniciado com sucesso! Status: $HTTP_STATUS"
          else
            echo "Falha ao iniciar deploy. Status: $HTTP_STATUS"
            exit 1
          fi
