name: Coolify Webhook Trigger

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install axios

      - name: Trigger Coolify Deploy
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');

            const deployUrl = 'https://dev.lkgiovani.com/api/v1/deploy?uuid=s8s0oksoks4c4s04ckckoggw&force=false';

            console.log(`Enviando requisição de deploy para ${deployUrl}`);

            try {
              const response = await axios.get(deployUrl);
              
              console.log(`Status: ${response.status}`);
              console.log('Deploy iniciado com sucesso!');
            } catch (error) {
              console.error('Erro ao iniciar deploy:', error.message);
              if (error.response) {
                console.error(`Status: ${error.response.status}`);
                console.error('Response:', error.response.data);
              }
              core.setFailed('Falha ao iniciar deploy no Coolify');
            }
