name: Coolify Webhook Trigger

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  deploy-prd:
    runs-on: ubuntu-latest
    environment: Production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Trigger Coolify Deploy
        run: |
          echo "Enviando requisição de deploy para Coolify..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -X GET \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
            "${{ secrets.COOLIFY_UUID }}api/v1/deploy?uuid=${{ secrets.COOLIFY_BASE_URL }}&force=${{ secrets.COOLIFY_FORCE_DEPLOY }}")

          if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
            echo "Deploy iniciado com sucesso! Status: $HTTP_STATUS"
          else
            echo "Falha ao iniciar deploy. Status: $HTTP_STATUS"
            exit 1
          fi
